# Site settings
title: 从现在行动
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "从现在行动|Do it now"  
baseurl: ""
url: "http://sanbuguan.github.io"  



# About/contact
owner: 
  name: " Ivan"
  email: lai-nn-1@qq.com
  bio: "从现在行动"

# Data
gavatar: 
favicon: img/favicon.ico
img_location: ""


douban_username:  
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins: [jekyll-paginate]
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ivan"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
# comments :
#   provider : disqus
#   duoshuo :
#     short_name : cnfeat
#   disqus :
#       short_name : cnfeat


# Links to include in footer navigation
